### ISSUE TITLE
Exception in UseUnderscoresForUnusedLambdaParametersAnalyzer

### ISSUE THREAD

**Issue by jnyrup** [bkoelman/CSharpGuidelinesAnalyzer#102]
#### Analyzer

UseUnderscoresForUnusedLambdaParametersAnalyzer

#### Repro steps

```csharp
public class Class1
{
    public event PropertyChangedEventHandler PropertyChanged = delegate { };
}
```
#### Expected behavior
no exceptions

#### Actual behavior
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at CSharpGuidelinesAnalyzer.Rules.Naming.UseUnderscoresForUnusedLambdaParametersAnalyzer.AnalyzeParameterUsage(IParameterSymbol parameter, IMethodSymbol method, OperationAnalysisContext context)
   at CSharpGuidelinesAnalyzer.Rules.Naming.UseUnderscoresForUnusedLambdaParametersAnalyzer.AnalyzeLambdaExpression(OperationAnalysisContext context)
   at CSharpGuidelinesAnalyzer.Extensions.AnalysisContextExtensions.SkipInvalid(OperationAnalysisContext context, Action`1 action)
   at CSharpGuidelinesAnalyzer.Rules.Naming.UseUnderscoresForUnusedLambdaParametersAnalyzer.<Initialize>b__8_0(OperationAnalysisContext c)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__44_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
```

**Comment by bkoelman** [comment]
Thanks for reporting.

I was able to repro this by pasting the code in a new project. A red squiggle appeared on `PropertyChangedEventHandler` because of a missing namespace import. Opening the lightbulb menu triggered the crash.

I am about to push a fix for this. Can you try if that works for you? Please wait a few minutes for the build to complete. See the main repo page, last section for how to install.

**Comment by jnyrup** [comment]
I tried out `CSharpGuidelinesAnalyzer.NuGetBugRequiresNewId.2.6.1-pre-10-master.nupkg` and this no longer throws an exception.
